import { create } from 'zustand'
import { persist } from 'zustand/middleware'

export type Language = 'en' | 'es' | 'de' | 'it' | 'hi' | 'ru'

interface LanguageState {
    language: Language
    setLanguage: (lang: Language) => void
}

export const useLanguageStore = create<LanguageState>()(
    persist(
        (set) => ({
            language: 'en',
            setLanguage: (lang) => set({ language: lang }),
        }),
        {
            name: 'language-storage',
        }
    )
)

export const translations = {
    en: {
        accessRestricted: 'Access Restricted',
        accessDeniedMsg: "You don't have permission to access the dashboard statistics.",
        permissionRequiredMsg: 'This area requires specific permissions that are not currently granted to your account.',
        hiddenStatsMsg: 'Dashboard statistics are hidden due to permission restrictions, Try switching to a different page.',
        contactAdminMsg: 'If you believe this is a mistake, please contact your administrator.',
        financialOverview: 'Financial Overview',
        totalBalance: 'Total Balance',
        totalSales: 'Total Sales',
        totalProfit: 'Total Profit',
        inventoryValue: 'Inventory Value',
        clientsPayable: "Company Client's Payable Balance (Clients owe to us)",
        companyPayable: "Company Payable Balance (Total Amount Owed to Clients)",
        companyBalances: 'Company Balances',
        startDate: 'Start Date',
        endDate: 'End Date',
        exitCustomize: 'Exit Customize',
        customizeLayout: 'Customize Layout',
        customizationMode: 'Customization Mode',
        dragMsg: 'Drag widgets to reorder your dashboard.',
        cash: 'Cash',
        eft: 'EFT',
        crypto: 'Crypto',
        all: 'All',
        update: 'Update',
        cancel: 'Cancel',
        add: 'Add',
        reason: 'Reason (optional)',
        addBalance: 'Add Balance',
        cashBalance: 'Cash Balance',
        eftBalance: 'EFT Balance',
        cryptoBalance: 'Crypto Balance',
        balanceUpdated: 'Balance updated successfully',
        accessDeniedToast: 'Access denied: You do not have permission to view dashboard statistics',
        errorFetchingStats: 'Error fetching stats',
        errorUpdatingBalance: 'Error updating balance',
    },
    es: {
        accessRestricted: 'Acceso Restringido',
        accessDeniedMsg: 'No tienes permiso para acceder a las estadísticas del tablero.',
        permissionRequiredMsg: 'Esta área requiere permisos específicos que no están otorgados actualmente a tu cuenta.',
        hiddenStatsMsg: 'Las estadísticas del tablero están ocultas debido a restricciones de permiso. Intenta cambiar a otra página.',
        contactAdminMsg: 'Si cree que esto es un error, póngase en contacto con su administrador.',
        financialOverview: 'Resumen Financiero',
        totalBalance: 'Saldo Total',
        totalSales: 'Ventas Totales',
        totalProfit: 'Ganancia Total',
        inventoryValue: 'Valor del Inventario',
        clientsPayable: 'Saldo por Cobrar de Clientes (Clientes nos deben)',
        companyPayable: 'Saldo por Pagar de la Empresa (Monto Total Adeudado a Clientes)',
        companyBalances: 'Saldos de la Empresa',
        startDate: 'Fecha de Inicio',
        endDate: 'Fecha de Fin',
        exitCustomize: 'Salir de Personalización',
        customizeLayout: 'Personalizar Diseño',
        customizationMode: 'Modo de Personalización',
        dragMsg: 'Arrastra los widgets para reordenar tu tablero.',
        cash: 'Efectivo',
        eft: 'EFT',
        crypto: 'Cripto',
        all: 'Todo',
        update: 'Actualizar',
        cancel: 'Cancelar',
        add: 'Añadir',
        reason: 'Razón (opcional)',
        addBalance: 'Añadir Saldo',
        cashBalance: 'Saldo de Efectivo',
        eftBalance: 'Saldo EFT',
        cryptoBalance: 'Saldo Cripto',
        balanceUpdated: 'Saldo actualizado con éxito',
        accessDeniedToast: 'Acceso denegado: No tienes permiso para ver las estadísticas del tablero',
        errorFetchingStats: 'Error al obtener estadísticas',
        errorUpdatingBalance: 'Error al actualizar el saldo',
    },
    de: {
        accessRestricted: 'Zugriff Eingeschränkt',
        accessDeniedMsg: 'Sie haben keine Berechtigung, auf die Dashboard-Statistiken zuzugreifen.',
        permissionRequiredMsg: 'Dieser Bereich erfordert spezifische Berechtigungen, die Ihrem Konto derzeit nicht erteilt wurden.',
        hiddenStatsMsg: 'Dashboard-Statistiken sind aufgrund von Berechtigungseinschränkungen ausgeblendet. Versuchen Sie, zu einer anderen Seite zu wechseln.',
        contactAdminMsg: 'Wenn Sie glauben, dass dies ein Fehler ist, wenden Sie sich bitte an Ihren Administrator.',
        financialOverview: 'Finanzübersicht',
        totalBalance: 'Gesamtbilanz',
        totalSales: 'Gesamtumsatz',
        totalProfit: 'Gesamtgewinn',
        inventoryValue: 'Lagerwert',
        clientsPayable: 'Ausstehende Kundensalden (Kunden schulden uns)',
        companyPayable: 'Verbindlichkeiten des Unternehmens (Gesamtbetrag gegenüber Kunden)',
        companyBalances: 'Unternehmensguthaben',
        startDate: 'Startdatum',
        endDate: 'Enddatum',
        exitCustomize: 'Anpassung Beenden',
        customizeLayout: 'Layout Anpassen',
        customizationMode: 'Anpassungsmodus',
        dragMsg: 'Ziehen Sie Widgets, um Ihr Dashboard neu anzuordnen.',
        cash: 'Bargeld',
        eft: 'EFT',
        crypto: 'Krypto',
        all: 'Alle',
        update: 'Aktualisieren',
        cancel: 'Abbrechen',
        add: 'Hinzufügen',
        reason: 'Grund (optional)',
        addBalance: 'Guthaben Hinzufügen',
        cashBalance: 'Bargeldbestand',
        eftBalance: 'EFT-Guthaben',
        cryptoBalance: 'Krypto-Guthaben',
        balanceUpdated: 'Guthaben erfolgreich aktualisiert',
        accessDeniedToast: 'Zugriff verweigert: Sie haben keine Berechtigung, Dashboard-Statistiken anzuzeigen',
        errorFetchingStats: 'Fehler beim Abrufen der Statistiken',
        errorUpdatingBalance: 'Fehler beim Aktualisieren des Guthabens',
    },
    it: {
        accessRestricted: 'Accesso Limitato',
        accessDeniedMsg: 'Non hai il permesso di accedere alle statistiche del dashboard.',
        permissionRequiredMsg: 'Questa area richiede permessi specifici che non sono attualmente concessi al tuo account.',
        hiddenStatsMsg: 'Le statistiche del dashboard sono nascoste a causa di restrizioni sui permessi. Prova a passare a un\'altra pagina.',
        contactAdminMsg: 'Se ritieni che si tratti di un errore, contatta il tuo amministratore.',
        financialOverview: 'Panoramica Finanziaria',
        totalBalance: 'Saldo Totale',
        totalSales: 'Vendite Totali',
        totalProfit: 'Profitto Totale',
        inventoryValue: 'Valore Inventario',
        clientsPayable: 'Saldo Da Ricevere Dai Clienti (I clienti ci devono)',
        companyPayable: 'Saldo Da Pagare Dell\'Azienda (Importo Totale Dovuto Ai Clienti)',
        companyBalances: 'Saldi Aziendali',
        startDate: 'Data Inizio',
        endDate: 'Data Fine',
        exitCustomize: 'Esci Personalizzazione',
        customizeLayout: 'Personalizza Layout',
        customizationMode: 'Modalità Personalizzazione',
        dragMsg: 'Trascina i widget per riordinare la tua dashboard.',
        cash: 'Contanti',
        eft: 'EFT',
        crypto: 'Cripto',
        all: 'Tutto',
        update: 'Aggiorna',
        cancel: 'Annulla',
        add: 'Aggiungi',
        reason: 'Motivo (opzionale)',
        addBalance: 'Aggiungi Saldo',
        cashBalance: 'Saldo Contanti',
        eftBalance: 'Saldo EFT',
        cryptoBalance: 'Saldo Cripto',
        balanceUpdated: 'Saldo aggiornato con successo',
        accessDeniedToast: 'Accesso negato: non hai il permesso di visualizzare le statistiche della dashboard',
        errorFetchingStats: 'Errore durante il recupero delle statistiche',
        errorUpdatingBalance: 'Errore durante l\'aggiornamento del saldo',
    },
    hi: {
        accessRestricted: 'पहुंच प्रतिबंधित',
        accessDeniedMsg: 'आपको डैशबोर्ड आंकड़ों तक पहुंचने की अनुमति नहीं है।',
        permissionRequiredMsg: 'इस क्षेत्र के लिए विशिष्ट अनुमतियों की आवश्यकता है जो वर्तमान में आपके खाते को नहीं दी गई हैं।',
        hiddenStatsMsg: 'अनुमति प्रतिबंधों के कारण डैशबोर्ड आंकड़े छिपे हुए हैं, किसी अन्य पृष्ठ पर जाने का प्रयास करें।',
        contactAdminMsg: 'यदि आपको लगता है कि यह एक गलती है, तो कृपया अपने व्यवस्थापक से संपर्क करें।',
        financialOverview: 'वित्तीय अवलोकन',
        totalBalance: 'कुल शेष',
        totalSales: 'कुल बिक्री',
        totalProfit: 'कुल लाभ',
        inventoryValue: 'इन्वेंटरी मूल्य',
        clientsPayable: 'ग्राहकों का देय शेष (ग्राहक हमारे ऋणी हैं)',
        companyPayable: 'कंपनी देय शेष (ग्राहकों को बकाया कुल राशि)',
        companyBalances: 'कंपनी शेष',
        startDate: 'आरंभ तिथि',
        endDate: 'अंतिम तिथि',
        exitCustomize: 'अनुकूलन से बाहर निकलें',
        customizeLayout: 'लेआउट अनुकूलित करें',
        customizationMode: 'अनुकूलन मोड',
        dragMsg: 'अपने डैशबोर्ड को पुनर्व्यवस्थित करने के लिए विजेट खींचें।',
        cash: 'नकद',
        eft: 'EFT',
        crypto: 'क्रिप्टो',
        all: 'सभी',
        update: 'अपडेट करें',
        cancel: 'रद्द करें',
        add: 'जोड़ें',
        reason: 'कारण (वैकल्पिक)',
        addBalance: 'शेष जोड़ें',
        cashBalance: 'नकद शेष',
        eftBalance: 'EFT शेष',
        cryptoBalance: 'क्रिप्टो शेष',
        balanceUpdated: 'शेष सफलतापूर्वक अपडेट किया गया',
        accessDeniedToast: 'पहुंच अस्वीकृत: आपको डैशबोर्ड आंकड़े देखने की अनुमति नहीं है',
        errorFetchingStats: 'आंकड़े प्राप्त करने में त्रुटि',
        errorUpdatingBalance: 'शेष राशि अपडेट करने में त्रुटि',
    },
    ru: {
        accessRestricted: 'Доступ ограничен',
        accessDeniedMsg: 'У вас нет прав для доступа к статистике панели управления.',
        permissionRequiredMsg: 'Этот раздел требует специальных разрешений, которые в данный момент не предоставлены вашей учетной записи.',
        hiddenStatsMsg: 'Статистика панели управления скрыта из-за ограничений прав доступа. Попробуйте переключиться на другую страницу.',
        contactAdminMsg: 'Если вы считаете, что это ошибка, обратитесь к администратору.',
        financialOverview: 'Финансовый обзор',
        totalBalance: 'Общий баланс',
        totalSales: 'Общий объем продаж',
        totalProfit: 'Общая прибыль',
        inventoryValue: 'Стоимость инвентаря',
        clientsPayable: 'Дебиторская задолженность клиентов (клиенты должны нам)',
        companyPayable: 'Кредиторская задолженность компании (общая сумма задолженности перед клиентами)',
        companyBalances: 'Балансы компании',
        startDate: 'Дата начала',
        endDate: 'Дата окончания',
        exitCustomize: 'Выйти из настройки',
        customizeLayout: 'Настроить макет',
        customizationMode: 'Режим настройки',
        dragMsg: 'Перетаскивайте виджеты, чтобы изменить порядок на панели управления.',
        cash: 'Наличные',
        eft: 'EFT',
        crypto: 'Крипто',
        all: 'Все',
        update: 'Обновить',
        cancel: 'Отмена',
        add: 'Добавить',
        reason: 'Причина (необязательно)',
        addBalance: 'Добавить баланс',
        cashBalance: 'Баланс наличных',
        eftBalance: 'Баланс EFT',
        cryptoBalance: 'Крипто баланс',
        balanceUpdated: 'Баланс успешно обновлен',
        accessDeniedToast: 'Доступ запрещен: у вас нет прав на просмотр статистики панели управления',
        errorFetchingStats: 'Ошибка при получении статистики',
        errorUpdatingBalance: 'Ошибка при обновлении баланса',
    },
}
